version: '3.8'

services:

  crm-db-service:
    container_name: crm_mysql_db_container
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '123'
      MYSQL_DATABASE: 'crm_db'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
  crm-web-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_webapp_container
    environment:
      spring.datasource.url: "jdbc:mysql://crm-db-service:3306/crm_db"
    depends_on:
      - crm-db-service
    ports:
      - '127.0.0.1:8080:8080'
    restart: always